  name: jenkins-job
  description: 'Start Jenkins job'
  branding:
      icon: "check"
      color: orange
  inputs:
      jenkins_job_name:
        description: 'Jenkins job name'
        required: true
      jenkins_base_url:
          description: 'Jenkins URL'
          required: true
      jenkins_user:
          description: 'Jenkins user'
          required: true
      jenkins_password:
          description: 'Jenkins password'
          required: true
  runs:
      image: "Dockerfile"
      using: "docker"
      args:
          - ${{ inputs.jenkins_job_name }}
          - --jenkins_base_url=${{ inputs.jenkins_base_url }}
          - --username=${{ inputs.jenkins_user }}
          - --password=${{ inputs.jenkins_password }}
