name: Run pre-commit checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Install poetry
        run: make install-poetry
      - name: Install dependencies
        run: make install
      - name: Run pre-commit
        run: make pre-commit
