name: Run pre-commit checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8.6
          architecture: x64
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run precommit
        run: pre-commit run --all-files
